package utils;

import java.io.Serializable;
import java.util.Comparator;
import utils.PP;

/**
 * Data type that holds two components
 */
public class Pair<A, B> implements Comparable<Pair>, Serializable
{
    private static final long serialVersionUID = 1L;

	public A o1;
    public B o2;

    public Pair(A o1, B o2)
    {
    	this.o1 = o1;
    	this.o2 = o2;
    }

    /**
     * Default ctor
     */
    public Pair()
    {
    	this(null, null);
    }

    // Autogenerated
	public int hashCode()
	{
		final int prime = 31;
		int result = 1;
		result = prime * result + ((o1 == null) ? 0 : o1.hashCode());
		result = prime * result + ((o2 == null) ? 0 : o2.hashCode());
		return result;
	}

    // Autogenerated
	public boolean equals(Object obj)
	{
		if (this == obj) return true;
		if (obj == null) return false;
		if (getClass() != obj.getClass()) return false;
		Pair other = (Pair) obj;
		if (o1 == null)
		{
			if (other.o1 != null) return false;
		}
		else if (!o1.equals(other.o1)) return false;
		if (o2 == null)
		{
			if (other.o2 != null) return false;
		}
		else if (!o2.equals(other.o2)) return false;
		return true;
	}

    public String toString()
    {
           return "Pair(" + PP.o2str(o1) + ", " + PP.o2str(o2) + ")";
    }

    public void set1(A o1)
    { this.o1 = o1; }

    public void set2(B o2)
    { this.o2 = o2; }

    /**
     * Compares only the first element, given that it's comparable
     */
	public int compareTo(Pair that)
	{
		return ((Comparable) this.o1).compareTo(that.o1);
	}

	/**
	 * Treats the i-th element as Comparable. i starts at 1 <br>
	 * Default comparator: first and ascending
	 */
	public static Comparator<Pair> comparator(final int i, final boolean ascending)
	{
		return new Comparator<Pair>()
		{
			public int compare(Pair p1, Pair p2)
			{
				return (ascending ? 1 : -1) *
							(i == 1 ? ((Comparable)p1.o1).compareTo(p2.o1) :
						  				((Comparable)p1.o2).compareTo(p2.o2));
			}
		};
	}
	public static Comparator<Pair> comparator() { return comparator(1, true); }
}
